#!/usr/bin/php
<?php
require __DIR__.'/../bootstrap.php';

use LoteriaApi\Config,
    LoteriaApi\Consumer\Download,
    LoteriaApi\Consumer\Extract,
    LoteriaApi\Consumer\Writer,
    LoteriaApi\Consumer\Reader,
    Kodify\DownloaderBundle\Service\Downloader,
    VIPSoft\Unzip\Unzip;    

$config = (new Config)
    ->setDirectory('etc')
    ->setExt('ini');

$paths = $config
    ->setFileName('path')
    ->getData();

$datasources = $config
    ->setFileName('datasource')
    ->getData();

(new Download())
    ->setComponent(new Downloader)
    ->setDataSource($datasources)
    ->setLocalStorage($paths['zip'])
    ->run();

(new Extract())
    ->setComponent(new Unzip)
    ->setDataSource($datasources)
    ->setLocalStorage($paths['ext'])    
    ->run();

$data = (new Reader)
    ->setDataSource($datasources)
    ->getData();

(new Writer)
    ->setDataSource($datasources)
    ->setData($data)    
    ->setLocalStorage($paths['xml'])    
    ->run();